import re
text="The rain in spain"
a=re.sub(r"\AThe","111",text)
print(a)
b=re.sub(r"\bain","111",text)
print(b)
c=re.sub(r"ain\b","111",text)
print(c)
d=re.sub(r"\Bain","111",text)
print(d)
e=re.sub(r"ain\B","111",text)
print(e)
f=re.sub("\d","111",text)
print(f)
g=re.sub("\D","111",text)
print(g)
h=re.sub("\s","111",text)
print(h)
i=re.sub("\S","111",text)
print(i)
j=re.sub("\w","111",text)
print(j)
k=re.sub("\W","111",text)
print(k)
l=re.sub("Spain\Z","111",text)
print(l)