import re
text="The rain in spain"
x=re.split("\AThe",text)
print(x)
a=re.split(r"\bain",text)
print(a)
b=re.split(r"ain\b",text)
print(b)
c=re.split(r"\Bain",text)
print(c)
d=re.split(r"ain\B",text)
print(d)
e=re.split("\d",text)
print(e)
f=re.split("\D",text)
print(f)
g=re.split("\s",text)
print(g)
h=re.split("\S",text)
print(h)
i=re.split("\W",text)
print(i)
j=re.split("\w",text)
print(j)
k=re.split("spain\Z",text)
print(k)