import re
text="The rain in spain"
a=re.search(r"\AThe",text)
print(a)
b=re.search(r"\bain",text)
print(b)
c=re.search(r"ain\b",text)
print(c)
d=re.search(r"\Bain",text)
print(d)
e=re.search(r"ain\B",text)
print(e)
f=re.search("\d",text)
print(f)
g=re.search("\D",text)
print(g)
h=re.search("\s",text)
print(h)
i=re.search("\S",text)
print(i)
j=re.search("\w",text)
print(j)
k=re.search("\W",text)
print(k)
l=re.search("Spain\Z",text)
print(l)