# f=open("sample.txt","x")
# f=open("sample.txt","a")
# print(f.read(5))
# print(f.readline())
# print(f.readlines())
# f.write("\n Good morning")
# f.close()
# f=open("sample.txt","r")
# print(f.read())
# f=open("sample.txt","w")
# f.write("Good evening")
# f.close()
# f=open("sample.txt","r")
# print(f.read())
# f=open("test.txt",'x')