import re
text="The rain in spain 21412"
a=re.match("\AThe",text)
print("A:",a)
b=re.match(r"\bain",text)
print(b)
c=re.match(r"ain\b",text)
print(c)
d=re.match(r"\Bain",text)
print(d)
e=re.match(r"ain\B",text)
print(e)
f=re.match("\d",text)
print(f)
g=re.match("\D",text)
print(g)
h=re.match("\s",text)
print(h)
i=re.match("\S",text)
print(i)
j=re.match("\w",text)
print(j)
k=re.match("\W",text)
print(k)